### ISSUE TITLE
Abstract/align recipes between drupal-vm and drupal-pi?

### ISSUE THREAD

**Issue by nateswart** [geerlingguy/drupal-pi#10]
It would be really cool to be able to use the same drupal recipes on a drupal vm setup and a drupal pi setup.  My ultimate goal would be to add other similar (but non-drupal) recipes as well to run on either platform, leveraging the same webstack.

Related, being able to run the drupalvm stack (with solr, varnish, etc) on the drupal-pi project would be really slick :)

Are any of these thoughts feasible?

**Comment by geerlingguy** [comment]
True. A lot of the roles work fine with Debian 7/8 (Wheezy/Jessie), but a couple are not as well tested on Debian as on RHEL/CentOS/Ubuntu.

I don't know if I'll move this project more towards a Drupal VM-like flexible model, but it's definitely easy enough to fork it and add the roles required to build a more fully-featured stack.

One major limitation, though: with a 1 GB RAM ceiling, anything beyond MySQL, Apache/Nginx, and PHP starts pushing the limits of what the Pi can comfortably deliver, especially with Drupal 8!

**Comment by geerlingguy** [comment]
I've done a _tiny_ bit of work on this between Drupal Pi and Drupal VM for the Nginx configuration... but I'm going to more closely align Drupal Pi with the Pi Dramble project, since my main concern with both of these projects is running Drupal 8 on the Pi—specifically with Debian Jessie (8), and I selfishly just want to use the same config between the two so I can switch between the full cluster and the single Pi as needed, when I take the cluster on the road.

Of course, I could go out and buy a second one, but that's a bit pricey!

**Comment by geerlingguy** [comment]
Right now I'm working on aligning things more closely between Drupal Pi and the [Raspberry Pi Dramble](http://www.pidramble.com/) project... I think I would still like to get some things meshed up with Drupal VM better too, but that's lower priority as the OS targets and environment needs are so much different on a Pi vs. a beefy local dev environment.
