### ISSUE TITLE
multiple instances and sites folders

### ISSUE THREAD

**Issue by Careless** [geerlingguy/drupal-pi#39]
is it possible to run multiple instances of the drupal-pi container/stack?

I am currently using portainer.io to try and duplicate the stack that the ansible script has installed along with docker, but I can't figure out how to replicate.

further, the "/var/drupal/files" folder is for items in the docker container that would normally show up in the "files" folder on any other Drupal installation, but where does one put or have access to modules, libraries, etc. folders for the default drupal-pi installation.

how can one develop the drupal site if the only exposed folder is the "files" folder and not the "sites" folder where one adds drupal modules/etc to when creating sites or applying module patches.

Don't we need access to those folders? I'm not sure how to achieve this.

**Comment by geerlingguy** [comment]
Right now I don't support multiple Drupal instances on the Drupal Pi (mostly because that's not my use case), but it is probably not super hard to do. I probably will not have time to work on such a feature though, so I'd recommend forking if you intend to maintain a Pi running multiple Drupal containers long term.

Also, this project is meant more for production use, not development use, therefore the files folder is the only thing that needs to be persistent (at least in the majority of cases).

There are arguments to be made about running Drupal in Docker in production in some other setups, but this is the most 12-factor way I can do it, so I'm trying to keep this project lean and not try supporting multiple other ways of running the sites.

The intention is that the Drupal site is being developed elsewhere (e.g. on your local laptop, on a different development pi, etc.), and then you build a Docker image with the production code once you've developed new features or made changes, and then you push that production docker image up to the Drupal Pi.

See this project for more of the lifecycle I'm targeting/envisioning: https://github.com/geerlingguy/drupal-for-kubernetes

Thanks for the ticket though!

**Comment by Careless** [comment]
> The intention is that the Drupal site is being developed elsewhere (e.g. on your local laptop, on a different development pi, etc.), and then you build a Docker image with the production code once you've developed new features or made changes, and then you push that production docker image up to the Drupal Pi.

can you elaborate on this?

how does one develop on a different development pi if drupal-pi installs the same way? how would one have access to those folders in order to build the site.

or moreover, how would someone turn an existing running local drupal site into a docker image (on say a computer within the LAN on a NAS with a web server) if it's currently running a device with web services that are not provided from Docker itself?

**Comment by geerlingguy** [comment]
@Careless - Please see the docs on the Drupal for Kubernetes project: https://github.com/geerlingguy/drupal-for-kubernetes/blob/master/docs/README.md

Note, however, that if you just add a `volume` to the Docker Compose file (as you do when developing on the Drupal for Kubernetes example site), you can run a local codebase instead of the codebase that's 'baked into' the Docker container.
